CREATE TABLE Genre
(
  GenreID INT(3) NOT NULL,
  GenreName VARCHAR(30) NOT NULL,
  PRIMARY KEY (GenreID)
);

CREATE TABLE BookName
(
  BookNameID INT(4) NOT NULL,
  BookName VARCHAR(255) NOT NULL,
  PRIMARY KEY (BookNameID)
);


CREATE TABLE ISBN
(
  ISBN VARCHAR(17) NOT NULL,
  BookID_(FK) INT(4) NOT NULL,
  BookID INT(4) NOT NULL,
  PRIMARY KEY (ISBN),
  FOREIGN KEY (BookID) REFERENCES Book(BookID),
  UNIQUE (BookID_(FK))
);


CREATE TABLE Book_Genre
(
  GenreID_(FK) INT(3) NOT NULL,
  BookID_(FK) INT(4) NOT NULL,
  GenreID INT(3) NOT NULL,
  BookID INT(4) NOT NULL,
  PRIMARY KEY (GenreID_(FK)),
  FOREIGN KEY (GenreID) REFERENCES Genre(GenreID),
  FOREIGN KEY (BookID) REFERENCES Book(BookID),
  UNIQUE (BookID_(FK))
);
